Feature/pre commit
baobao1270/vscode-markdown-mindmap-preview pull request #15
Opened 2021-05-24 14:16 UTC by engvucen

A editor/husky

2021-05-25 16:55 UTC, baobao1270 requested changes
I have revert your commit related to husky, for we are not prepared to add git hooks as linting now. I think it may involve extra work, now `eslint` is just enough.

2021-05-25 16:55 UTC, baobao1270 commented on src/mindMapPreviewWebview.ts
> +    isFromFile: any = { fromFile: false };
Why you are naming a object with `is` prefix? It will be confusing.

2021-05-25 16:55 UTC, baobao1270 commented on src/mindMapPreviewWebview.ts
> +        disposables.push(vscode.workspace.onDidChangeTextDocument(debounceFunc));
This function is designed to not declare any variables. Please change the code style to this:

```suggestion
        disposables.push(vscode.workspace.onDidChangeTextDocument(utils.debounce(
                this,
                () => { this.updatePreview.call(this, this.isFromFile);  },
                2000 //please describe what does this 2000 mean.
        )));
```

2021-05-25 16:55 UTC, baobao1270 commented on src/mindMapPreviewWebview.ts
> +    updatePreview(conf = { fromFile: false }) {
You are making the code complex. Just simply write like this:
```suggestion
    updatePreview(isFormFile: bool = false) {
        const data = isFromFile ?
            utils.getMarkDownTitle(data) : this.editingEditor.document.getText();
        this.view.webview.postMessage({ command: "renderMarkdown", data: data });
}
```

If you have to use the `conf` variable, please describe why.

2021-05-25 17:03 UTC, baobao1270 commented
After change please describe how to use the feature you add, so that I can edit README and keep it documented.

Checklist:
 - [ ] Change your code
 - [ ] Provide description of your added feature (both in README with detail or in this PR comment in few words are OK)
 - [ ] Test (by @baobao1270)
 - [ ] Update version to `1.3.0` (by @baobao1270) and merge to `master`
 - [ ] Release new version to VSCode Marketplace

2021-05-26 14:24 UTC, engvucen commented on src/mindMapPreviewWebview.ts
> +        disposables.push(vscode.workspace.onDidChangeTextDocument(debounceFunc));
原来的代码，没有“节流”，即使敲下一个字符，也会重新渲染脑图，有点浪费性能；
添加“节流”，现在的表现是：用户停止输入后的2秒后，才重新渲染脑图。

2021-05-26 14:27 UTC, engvucen commented on src/mindMapPreviewWebview.ts
> +    updatePreview(conf = { fromFile: false }) {
为了方便扩展参数，语义上更清晰：
1. updatePreview({ isFormFile: true, otherFlag: [] }); 有 Key 名，能够知道添加参数的意义；
2. 个人觉得比这种形式好： updatePreview(true, []);

2021-05-26 17:08 UTC, baobao1270 commented on src/mindMapPreviewWebview.ts
> +    isFromFile: any = { fromFile: false };
```suggestion
    isFromFile: bool = false;
```

2021-05-26 17:09 UTC, baobao1270 commented on src/mindMapPreviewWebview.ts
> +        disposables.push(vscode.workspace.onDidChangeTextDocument(debounceFunc));
好的，请您使用
```typescript
2000 // Throttle 2000ms before rerending.
```
进行注释，谢谢。

另外个人还是希望这个函数内不要新增变量，你看一下我 suggest 的代码能不能跑，如果能的话就不要声明新的变量了。

2021-05-26 17:09 UTC, baobao1270 commented on src/mindMapPreviewWebview.ts
> +    updatePreview(conf = { fromFile: false }) {
1. 个人认为没有必要过早优化，使用单个参数已经足够，若今后需要扩展，可以再重构。
 2. 注意到，该函数是一个类的方法，故若能从实例中取值，则不应以方法取值。
     ```suggestion
         updatePreview() {
             const data = this.isFromFile ? utils.getMarkDownTitle(data)
                                          : this.editingEditor.document.getText();
         }
     ```
 3. 目前来看使用三元表达式是可取的，惟需再在增加更多判断条件时重构。

2021-05-27 05:34 UTC, engvucen commented
> After change please describe how to use the feature you add, so that I can edit README and keep it documented.
> 
> Checklist:
> 
> * [ ]  Change your code
> * [ ]  Provide description of your added feature (both in README with detail or in this PR comment in few words are OK)
> * [ ]  Test (by @baobao1270)
> * [ ]  Update version to `1.3.0` (by @baobao1270) and merge to `master`
> * [ ]  Release new version to VSCode Marketplace (by @baobao1270)



> After change please describe how to use the feature you add, so that I can edit README and keep it documented.
> 
> Checklist:
> 
> * [ ]  Change your code
> * [ ]  Provide description of your added feature (both in README with detail or in this PR comment in few words are OK)
> * [ ]  Test (by @baobao1270)
> * [ ]  Update version to `1.3.0` (by @baobao1270) and merge to `master`
> * [ ]  Release new version to VSCode Marketplace (by @baobao1270)

**预览思维导图**
1. 在 VSCode 中新建或打开一个文件。
2. 使用 Ctrl+Shift+P 快捷键打开命令面板，输入 Mind Map From File 命令。插件将提取文件中的 Markdown 标题文本，并按照标题层次构造思维导图，该导图显示在您编辑器右侧。
3. 若您更改左侧源文件，停止修改后的2秒后，右侧的思维导图将同步更改。
4. 您亦可使用鼠标滚轮随意缩放思维导图。

**将 Markdown 标题写入到粘贴板**
1. 在 VSCode 中新建或打开一个文件。
2. 使用 Ctrl+Shift+P 快捷键打开命令面板，输入 Copy Title From File 命令。插件将提取文件中的 Markdown 标题文本，将其写入到您的粘贴板中。
3. 这些文本，您可将其粘贴到 .md 文件，使用 Xmind 导入，进行后期处理。

2021-05-27 06:30 UTC, baobao1270 approved these changes

2021-05-31 14:44 UTC, merged